# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-28 10:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '__first__'),
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='cities',
            field=models.ManyToManyField(related_name='cleaners', to='cities.City'),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
