# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-03 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_auto_20170328_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='quality_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
